name: Deploy static content to Pages
on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

# Add separate concurrency groups for each job
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-${{ github.job }}"
  cancel-in-progress: false

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      # Add error handling for Elocuent
      - name: Run Elocuent
        run: |
          npx elocuent -d . -o meta/loc.csv || exit 1

      # Improve git operations with better error handling
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mkdir -p meta
          git add -f meta/loc.csv
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update code statistics"
            git pull --rebase --autostash
            git push || (git pull --rebase && git push)
          fi

  deploy:
    needs: update-stats
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    # Add retry logic for deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Add fetch-depth to ensure we have the latest changes
          fetch-depth: 1

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      # Add retry logic for deployment
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          timeout: 600000  # Increase timeout to 10 minutes